name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman newman-reporter-html

    - name: Run Postman Tests
      run: newman run Colleration.postman_collection -r cli,html --reporter-html-export report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: postman-test-report
        path: report.html
